# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y

CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=50

CONFIG_PROSPECTOR_DISPLAY_SLEEP_ENABLE=y
# Set the display idle timeout to 10 minutes
CONFIG_PROSPECTOR_DISPLAY_IDLE_TIMEOUT_MS=600000